services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: finova
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: npm run dev
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/finova
      OPENAI_API_KEY: ""
      PORT: 4000
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - '4000:4000'
    depends_on:
      - db
volumes:
  db_data:
